### PR TITLE
Fix issue #27

### LINKED ISSUE #27: Refactor generate_config_solar function
**Describe the bug**
Refactor the ```generate_config_solar``` function in the file ```flowy/lib.rs```. The function is just a nightmare to look at in it's current state. While it gets the job done, it can also look nice while still doing its job.

### PR DESCRIPTION
**Pull request by Baldomo**
Commit message: 

> Refactored generate_config_solar (removed String conversions, calculations now in seconds and absolute epochs), refactored unix_to_normal_time into public unix_to_local (now excludes formatting, just returns a Datetime<Local>), added a method Timetable::get(&SolarTime) to get values from the internal Map

### CODE REVIEW

File: flowy/src/lib.rs [hunk 1]
```diff
@@ -67,35 +67,40 @@ pub fn get_dir(path: &Path, solar_filter: &str) -> Result<Vec<String>, Box<dyn E
...
+    let day_div = day_len / day_walls.len() as i64;
+    // Offset in seconds for each wallpaper change during the night
+    let night_div = night_len / night_walls.len() as i64;
     let mut times = Vec::new();
 
-    for _ in 0..day_walls.len() {
-        times.push(format!("{}:{}", sunrise / 60, sunrise % 60));
-        sunrise = (sunrise + day_div) % 1440;
+    for i in 0..day_walls.len() {
+        let absolute = sunrise + (i as i64) * day_div;
```
Comment (vineetred) [inline flowy/src/lib.rs]: For better BODMAS comprehension, just change this expression to ``` (day_div * ( i as i64))```

**Review by vineetred — CHANGES_REQUESTED** [review]
While the changes are good and make the entire thing more Rust-y, the earlier logic was similar to how to the ```generate_config``` function behaved as well. The proposed changes makes the ```generate_config_solar``` inner workings quite different. Do you think you can change the ```generate_config``` as well to make it similar to these changes?

File: flowy/src/lib.rs [hunk 2]
```diff
@@ -67,35 +67,40 @@ pub fn get_dir(path: &Path, solar_filter: &str) -> Result<Vec<String>, Box<dyn E
...
-    let night_len = 1440 - day_len;
-    let day_div = day_len / day_walls.len() as u32;
-    let night_div = night_len / night_walls.len() as u32;
+    let sunrise = tt.get(&solar::SolarTime::Sunrise).unwrap().round() as i64;
+    let sunset = tt.get(&solar::SolarTime::Sunset).unwrap().round() as i64;
+
+    // Day length in seconds
+    let day_len = sunset - sunrise;
+    // Night length in seconds
+    let night_len = 86400 - day_len;
```
Comment (vineetred) [inline flowy/src/lib.rs]: Add a ``` % 86400``` at the end of the paranthesized statements so that we do not have to worry about the values being more that the number of seconds in a day

File: flowy/src/solar.rs [hunk 3]
```diff
@@ -156,14 +156,24 @@ impl Timetable {
...
+        self.timetable.get(st)
+    }
+
     /// Simple function to retrieve only sunset and sunrise times
     /// Returns a tuple (sunrise, sunset)
     pub fn get_sunrise_sunset(&self) -> (String, String) {
         // Index into the HashMap using SolarTime Enum
         let sunrise: String =
-            unix_to_normal_time(self.timetable.get(&SolarTime::Sunrise).unwrap().round() as i64);
+            unix_to_local(self.timetable.get(&SolarTime::Sunrise).unwrap().round() as i64)
```
Comment (vineetred) [inline flowy/src/solar.rs]: This function now has been deprecated?

Comment (Baldomo) [reply flowy/src/solar.rs]: No, I just renamed it and delegated the String formatting to the caller. This way any function that needs time formatting can just use any format. I think I could make it simpler/less verbose to use making it receive the format string code as a parameter then formatting internally

Comment (vineetred) [reply flowy/src/solar.rs]: What I mean is -- where are we using this function? I don't see it in the code? If it is useless, let's deprecate it?

Comment (vineetred) [reply flowy/src/solar.rs]: Actually, I would suggest you just change the way we get sunrise and sunset times in flowy/lib.rs and keep using this function as it allows for a higher level of abstraction.

Comment (Baldomo) [reply flowy/src/solar.rs]: The only place this function was used in was `generate_config_solar` but my implementation does not use it anymore. And if you're referring to lines 81-82, I already changed them to use seconds directly

Comment (vineetred) [reply flowy/src/solar.rs]: Yes I know that. I am asking you to change your implementatio so that ```generate_config_solar``` uses it  ```get_sunrise_sunset``` again

Comment (Baldomo) [reply flowy/src/solar.rs]: Sure! Will do asap

Comment (vineetred) [reply flowy/src/solar.rs]: Great! Just refactor ```get_sunrise_sunset``` to ensure it works with you changes.

File: flowy/src/lib.rs [hunk 4]
```diff
@@ -117,13 +117,13 @@ pub fn generate_config_solar(path: &Path, lat: f64, long: f64) -> Result<(), Box
...
+    let div = 86400 / walls.len();
     let mut times = Vec::new();
-    let mut start_sec = 0;
-    for _ in 0..length {
-        times.push(format!("{:02}:{:02}", start_sec / 60, start_sec % 60));
-        start_sec += div;
+
+    for i in 0..walls.len() {
+        let offset = div * i;
+        times.push(format!("{:02}:{:02}", offset / 3600, (offset / 60) % 60));
```
Comment (vineetred) [inline flowy/src/lib.rs:125]: Will this statement push times in the form ```18:32```?  I just want to know if the program is run in the normal ```--dir``` mode, it still works as expected.

**Review by vineetred — CHANGES_REQUESTED** [review]

File: flowy/src/lib.rs (hunk 4 above)
Comment (vineetred) [reply flowy/src/lib.rs:125]: Run it on your local and ```cat``` into the ```config.toml```file to see if everything has been generated right @Baldomo

Comment (Baldomo) [reply flowy/src/lib.rs:125]:
```toml
times = ["00:00", "06:00", "12:00", "18:00"]
walls = ["file:///home/leo/Pictures/Wallpapers/Ghibli Dynamic/DAY-01.jpeg", "file:///home/leo/Pictures/Wallpapers/Ghibli Dynamic/DAY-02.jpeg", "file:///home/leo/Pictures/Wallpapers/Ghibli Dynamic/DAY-03.jpeg", "file:///home/leo/Pictures/Wallpapers/Ghibli Dynamic/NIGHT-01.jpeg"]
```
Looks fine to me (`--dir` mode)

Comment (Baldomo) [reply flowy/src/lib.rs:125]:
```toml
times = ["05:48", "10:55", "16:02", "21:09"]
walls = ["file:///home/leo/Pictures/Wallpapers/Ghibli Dynamic/DAY-01.jpeg", "file:///home/leo/Pictures/Wallpapers/Ghibli Dynamic/DAY-02.jpeg", "file:///home/leo/Pictures/Wallpapers/Ghibli Dynamic/DAY-03.jpeg", "file:///home/leo/Pictures/Wallpapers/Ghibli Dynamic/NIGHT-01.jpeg"]
```
And this is `--solar` mode (coordinates `45.4668 9.1905`, Milan)

**Comment by vineetred** [comment]
Refactored generate_config_solar and other functions.
