### PR TITLE
Fix #10

### LINKED ISSUE #10: Wallpaper isn't set initially when starting flowy
**Describe the bug**
The wallpaper is updated at certain times of the day, but is in _not_ updated when initially starting `flowy`.

**To Reproduce**
1. Run `flowy -p lake`

**Expected behavior**
The wallpaper changes

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - DE: KDE 5.70.0 / Plasma 5.18.5
 - WM: KWin
 - Version: `master` branch

### PR DESCRIPTION
**Pull request by Aloso**
This fixes #10. It adds no new dependencies (`chrono` is already in the dependency tree).

Note that this will probably cause a merge conflict with #16.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -115,3 +121,13 @@ pub fn set_times(config: Config) {
         thread::sleep(Duration::from_secs(60));
     }
 }
+
+fn get_current_wallpaper(wall_len: usize) -> usize {
```
Comment (vineetred) [inline src/lib.rs]: Just comment on what this function does. Also, the name is quite similar to ```get_wallpaper()```, so I suggest we use a different function name. However, I leave this up to you.

**Review by vineetred — CHANGES_REQUESTED** [review]

File: src/lib.rs (hunk 1 above)
Comment (Aloso) [reply src/lib.rs]: This is resolved in the latest commit.

**Review by vineetred — APPROVED** [review]
Approved for merging.
